- hosts: localhost
  tasks:

  - name: Read Nexus Repository
    shell: python /Users/smartin/Ansible-Sant/test.py | grep name | awk -F ":" {'print $2'} | sed -e 's/"//g' | sed -e 's/,//g'  > /Users/smartin/Ansible-Sant/kk.log