- hosts: localhost
  tasks:

  - name: Create a k8s namespace
    community.kubernetes.k8s:
      name: nexus
      api_version: v1
      kind: Namespace
      state: present



  - name: Create a Deployment by reading the definition from a local file
    community.kubernetes.k8s:
      state: present
      src: ./deployment.yml



  - name: Create a Service object from an inline definition
    kubernetes.core.k8s:
      state: present
      definition:
        apiVersion: v1
        kind: Service
        metadata:
          name: nexus-service
          namespace: nexus
           # annotations:
           #   prometheus.io/scrape: 'true'
           #   prometheus.io/path:   /
           #   prometheus.io/port:   '8081'
        spec:
          selector:
            app: nexus-server
          type: NodePort
          ports:
            - port: 8081
              targetPort: 8081
              nodePort: 32000
 

 
