name: deploy to aks cluster

on:
  push:
    branches:
      - master

jobs:
  checking:
    name: Checking configuration
    runs-on: [ ubuntu-latest ]
    environment: development
    steps:
      - name: Check env variables
        run: |
          if [[ -z "${{secrets.K8S_SECRET}}" ]]; then
            echo "Define environment variable K8S_SECRET in github environments"
            exit 1
          fi

  deploy_ansible:
    name: launch ansible to deploy to k8s
    runs-on: [ ubuntu-latest ]
    environment: development
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: create Kube Config folder
        run: |
          mkdir -p $HOME/.kube
          cp ./ansible/files/config $HOME/.kube/config

      - name: Deploy Nexus service with Ansible
        run: |
          sudo apt install -y ansible
          ansible-playbook ./playbooks/deploy_nexus_kubernetes.yml
       