name: deploy to aks cluster

on:
  push:
    branches:
      - master

jobs:
  checking:
    name: Checking configuration
    runs-on: [ ubuntu-latest ]
    environment: development
    steps:
      - name: Check env variables
        run: |
          if [[ -z "${{secrets.K8S_SECRET}}" ]]; then
            echo "Define environment variable K8S_SECRET in github environments"
            exit 1
          fi

  config_k8s_env:
    name: launch ansible to deploy to k8s
    runs-on: [ ubuntu-latest ]
    environment: development
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      - name: create Kube Config folder
        run: |
          mkdir -p $HOME/.kube
          cp ./ansible/files/config $HOME/.kube/config

  deploy_ansible:
    name: deploy
    needs: config_k8s_env
    runs-on: [ ubuntu-latest ]
    environment: development
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2

      #- name: setup python
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: '3.x'
      
     # - name: python dependencies
      #  run:
         #python -m pip install -r ./ansible/files/requirements.txt


      - name: Deploy Nexus service with Ansible
        run: |
          sudo apt install -y ansible
          ansible-galaxy collection install community.kubernetes
          pip3 install kubernetes --user
          ansible-playbook ./ansible/playbooks/deploy_nexus_kubernetes.yml
